-- AlterTable
ALTER TABLE `Flashcard` ADD COLUMN `knowledge` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `FlashcardSet` ADD COLUMN `deleted` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `last_opened` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Note` ADD COLUMN `last_opened` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
